[build]
  command = "npm run build"
  publish = "build/client"

# This single redirect handles ALL client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

# Enable prerendering for SEO is handled by React Router
# No need for the Next.js plugin