[build]
  command = "npm run build"
  publish = "dist"

# Handle client-side routing - this should be last!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"