[build]
  command = "npm run build"
  publish = "build/client"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Specific route redirects
[[redirects]]
  from = "/enterprise"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/templates"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Add headers for sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

# Enable prerendering for SEO is handled by React Router
# No need for the Next.js plugin